version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_room
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python:
    container_name: python
    build: .
    env_file:
      - ./app/.env
    working_dir: /code/app
    command: uvicorn main:app --host 0.0.0.0 --reload
#    command: bash -c "tail -f /dev/null"
    volumes:
      - ./app:/code/app
    environment:
      DEBUG: 1
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - postgres


volumes:
  postgres_data: